### ISSUE TITLE
侧边栏无夜间模式的按钮

### ISSUE THREAD

**Issue by GIWTO** [1v9/hexo-next-nightmode#4]
请问按照README上的步骤配置完后，enable改为true后，之后还需要什么操作吗？我做完一切后我的博客上并没有显示夜间模式按钮。

**Comment by 1v9** [comment]
@taopaperman 你好,抱歉回复比较晚,另外已收到你的邮件.我一直使用最新的 next master 版本,另外此插件核心代码很简单一直没有变动,可以加入 https://t.me/theme_next_chinese 方便交流.

**Comment by GIWTO** [comment]
心累，不知道以前改了什么，现在只能重新配置一遍才能用上夜间模式了
