### ISSUE TITLE
夜间模式无法启用，以及

### ISSUE THREAD

**Issue by NLasagna** [1v9/hexo-next-nightmode#9]
我装上以后，并不能找到如何切换模式。我的站关闭了 sidebar，并且 mac 访问时试了 ctrl/opt/cmd + X 都不能切换。

readme 里讲 both in Hexo config or next config，是 both 还是 or？如果两个都要有，代码还要保持同步？

然后这个难道不是靠 prefers-color-scheme 来切换的吗？没有自动切换功能吗？

**Comment by 1v9** [comment]
配置只需一处，alpha 开启时夜间模式仅受设备的 prefers-color-scheme 设置控制，alpha 关闭时可以点击边栏按钮或者使用热键。

**Comment by NLasagna** [comment]
好。建议修改一下 readme 和 config 的注释，断句断得我就误会了
